spring:
  application:
    name: manager-app
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: market-manager-app
          service-host-type: ip
        url: http://localhost:8086
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace_db
    username: postgres
    password: 1199
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/market
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: 6NDGsTaDAz1UMUHwzZVvUamcfMThD1z3
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
          metrics:
            provider: keycloak
            client-id: manager-app
            client-secret: 6NDGsTaDAz1UMUHwzZVvUamcfMThD1z3
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
      resourceserver:
          jwt:
            issuer-uri: http://localhost:8082/realms/market

server:
  port: 8083


catalogue:
  service:
    url: http://localhost:8081
    username: product_service
    password: 1199
    registration: keycloak

logging:
  level:
    org.springframework.security: DEBUG

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'