spring:
  application:
    name: catalogue-sevice

  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace_db
    username: postgres
    password: 1199
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/market


server:
  port: 8081