spring:
  boot:
    admin:
      client:
        enabled: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: products
    create-schemas: true
    baseline-on-migrate: true
    jpa:
      hibernate:
        ddl-auto: validate  # или none вместо update
      defer-datasource-initialization: true

  application:
    name: catalogue-sevice

  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: postgres
    password: 1199
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.1.5:8082/realms/market
      client:
        registration:
          keycloak:
            client-id: catalogue-service-metrics-client
            client-secret: enjlURxtE37gXjHH7yx3tUZdqaEHRmP0
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
        provider:
          keycloak:
            issuer-uri: http://192.168.1.5:8082/realms/market


server:
  port: 8081

springdoc:
  swagger-ui:
    oauth:
      client-id: catalogue-service-swagger-ui
      use-pkce-with-authorization-code-grant: true

keycloak:
  uri: http://192.168.1.5:8082

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.5:8761/eureka/
  instance:
    hostname: 192.168.1.5  # или ваш корректный hostname
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
